[2025-07-21T01:36:19Z] ERROR bot [inst=DOGE-USDT-SWAP] [sess=b219b3ebd809407c9fc345f29c14ebdd] [mode=MAIN] [err=-]: ðŸ’¥ Fatal error: PreHedgeWatcher.__init__() got an unexpected keyword argument 'rest_client'
Traceback (most recent call last):
  File "d:\Develop\Python\trade_bot\11.8.3\main.py", line 107, in <module>
    asyncio.run(main())
  File "C:\Users\Professional\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Professional\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Professional\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "d:\Develop\Python\trade_bot\11.8.3\main.py", line 89, in main
    orchestrator = Orchestrator(
                   ^^^^^^^^^^^^^
  File "d:\Develop\Python\trade_bot\11.8.3\orchestrator.py", line 29, in __init__
    self.tp_watcher     = PreHedgeWatcher(
                          ^^^^^^^^^^^^^^^^
TypeError: PreHedgeWatcher.__init__() got an unexpected keyword argument 'rest_client'
